// Code generated by "stringer -type token -linecomment token.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Name-1]
	_ = x[Literal-2]
	_ = x[Assign-3]
	_ = x[Define-4]
	_ = x[Receive-5]
	_ = x[Star-6]
	_ = x[Not-7]
	_ = x[Tilde-8]
	_ = x[OrOr-9]
	_ = x[AndAnd-10]
	_ = x[Eql-11]
	_ = x[Neq-12]
	_ = x[Lss-13]
	_ = x[Leq-14]
	_ = x[Gtr-15]
	_ = x[Geq-16]
	_ = x[Add-17]
	_ = x[Sub-18]
	_ = x[Or-19]
	_ = x[And-20]
	_ = x[Xor-21]
	_ = x[AndNot-22]
	_ = x[Mul-23]
	_ = x[Div-24]
	_ = x[Rem-25]
	_ = x[Shl-26]
	_ = x[Shr-27]
	_ = x[Op-28]
	_ = x[AssignOp-29]
	_ = x[IncOp-30]
	_ = x[Lparen-31]
	_ = x[Lbracket-32]
	_ = x[Lbrace-33]
	_ = x[Rparen-34]
	_ = x[Rbracket-35]
	_ = x[Rbrace-36]
	_ = x[Comma-37]
	_ = x[Semi-38]
	_ = x[Colon-39]
	_ = x[Dot-40]
	_ = x[DotDotDot-41]
	_ = x[Package-42]
	_ = x[Import-43]
	_ = x[Sealed-44]
	_ = x[Class-45]
	_ = x[Interface-46]
	_ = x[Abstract-47]
	_ = x[Fn-48]
	_ = x[Enum-49]
	_ = x[Public-50]
	_ = x[Protect-51]
	_ = x[Private-52]
	_ = x[Defer-53]
	_ = x[Const-54]
	_ = x[GOTO-55]
	_ = x[This-56]
	_ = x[Super-57]
	_ = x[Return-58]
	_ = x[Break-59]
	_ = x[Continue-60]
	_ = x[Except-61]
	_ = x[For-62]
	_ = x[Do-63]
	_ = x[While-64]
	_ = x[If-65]
	_ = x[Else-66]
	_ = x[When-67]
	_ = x[Case-68]
	_ = x[Default-69]
	_ = x[Static-70]
	_ = x[Throws-71]
	_ = x[Throw-72]
	_ = x[Print-73]
	_ = x[Printf-74]
	_ = x[Println-75]
	_ = x[Nil-76]
	_ = x[Chan-77]
	_ = x[Run-78]
	_ = x[EOF-79]
	_ = x[ERROR-80]
}

const _token_name = "nameliteral=:=<-*!~||&&==!=<<=>>=+-|&^&^*/%<<>>opop=opop([{)]},;:....packageimportsealedclassinterfaceabstractfnenumpublicprotectprivatedeferconstgotothissuperreturnbreakcontinueexceptfordowhileifelsewhencasedefaultstaticthrowsthrowprintprintfprintlnnilchanrunEOFerror"

var _token_index = [...]uint16{0, 4, 11, 12, 14, 16, 17, 18, 19, 21, 23, 25, 27, 28, 30, 31, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 45, 47, 49, 52, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 76, 82, 88, 93, 102, 110, 112, 116, 122, 129, 136, 141, 146, 150, 154, 159, 165, 170, 178, 184, 187, 189, 194, 196, 200, 204, 208, 215, 221, 227, 232, 237, 243, 250, 253, 257, 260, 263, 268}

func (i token) String() string {
	i -= 1
	if i >= token(len(_token_index)-1) {
		return "token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
